'use server';

import { supabase } from '@/lib/supabase';
import { signUpSchema, loginSchema } from '@/lib/validations';
import { z } from 'zod';
import { redirect } from 'next/navigation';

type SignUpInput = z.infer<typeof signUpSchema>;
type LoginInput = z.infer<typeof loginSchema>;

/**
 * Sign up a new user with email and password
 * Automatically creates a profile with referral code
 */
export async function signUp(input: SignUpInput) {
  try {
    // Validate input
    const { email, password } = signUpSchema.parse(input);

    // Create Supabase auth user
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
    });

    if (authError) {
      return {
        error: authError.message,
        data: null,
      };
    }

    if (!authData.user) {
      return {
        error: 'Failed to create user',
        data: null,
      };
    }

    // Extract school domain from email
    const domain = email.split('@')[1];

    // Find school by domain
    const { data: schoolData, error: schoolError } = await supabase
      .from('schools')
      .select('id')
      .eq('domain', domain)
      .single();

    if (schoolError || !schoolData) {
      // If school not found, user can still sign up but won't have school assigned
      // In real scenario, may want to reject or show warning
      console.warn(`School domain not found: ${domain}`);
    }

    // Create profile (referral code generated by trigger)
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .insert({
        id: authData.user.id,
        email,
        school_id: schoolData?.id,
        role: 'student',
      })
      .select()
      .single();

    if (profileError) {
      // Clean up auth user if profile creation fails
      await supabase.auth.admin.deleteUser(authData.user.id);
      return {
        error: `Failed to create profile: ${profileError.message}`,
        data: null,
      };
    }

    return {
      error: null,
      data: {
        userId: authData.user.id,
        email: authData.user.email,
        profileId: profileData.id,
      },
    };
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        error: error.errors[0].message,
        data: null,
      };
    }
    return {
      error: error instanceof Error ? error.message : 'An error occurred',
      data: null,
    };
  }
}

/**
 * Log in an existing user
 */
export async function login(input: LoginInput) {
  try {
    // Validate input
    const { email, password } = loginSchema.parse(input);

    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (error) {
      return {
        error: error.message,
        data: null,
      };
    }

    if (!data.user) {
      return {
        error: 'Failed to log in',
        data: null,
      };
    }

    // Fetch profile to check if setup is complete
    const { data: profileData, error: profileError } = await supabase
      .from('profiles')
      .select('first_name, last_initial')
      .eq('id', data.user.id)
      .single();

    if (profileError) {
      return {
        error: 'Profile not found',
        data: null,
      };
    }

    // Check if profile is set up (has first_name)
    const isSetUp = !!profileData?.first_name;

    return {
      error: null,
      data: {
        userId: data.user.id,
        email: data.user.email,
        isProfileSetUp: isSetUp,
      },
    };
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        error: error.errors[0].message,
        data: null,
      };
    }
    return {
      error: error instanceof Error ? error.message : 'An error occurred',
      data: null,
    };
  }
}

/**
 * Log out the current user
 */
export async function logout() {
  try {
    const { error } = await supabase.auth.signOut();

    if (error) {
      return {
        error: error.message,
      };
    }

    redirect('/login');
  } catch (error) {
    return {
      error: error instanceof Error ? error.message : 'An error occurred',
    };
  }
}

/**
 * Get current authenticated user
 */
export async function getCurrentUser() {
  try {
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();

    if (error || !user) {
      return null;
    }

    return user;
  } catch {
    return null;
  }
}
